name: muatmuat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  device_apps: 2.1.1
  flutter_switch: 0.3.2
  pull_to_refresh: 2.0.0
  marquee: 1.7.0
  flutter_map_marker_cluster: 0.3.4
  dio: 3.0.9
  flutter_map_marker_popup: 0.2.1
  webview_flutter: 1.0.7
  url_launcher: ^5.4.11
  flutter_statusbar_manager: 2.0.0
  firebase_analytics: 6.1.0
  search_choices: 1.0.17
  searchable_dropdown: 1.1.3
  permission_handler: 5.1.0+2
  uuid: 2.2.2
  auto_size_text: 2.1.0
  keyboard_visibility: 0.5.6  
  image_picker: 0.6.7+22
  geocoding: 1.0.5
  geolocator: 6.1.14  
  share: 0.6.5+4
  path_provider: 1.6.24
  sqflite: 1.3.2+1
  flutter_html: 1.3.0
  connectivity: 2.0.2
  flutter_svg: ^0.20.0-nullsafety.3
  icon_font_generator: 1.0.0
  carousel_slider: 2.3.1
  flutter_countdown_timer: 1.5.0
  intl: 0.16.1
  shared_preferences: 0.5.12+4
  cool_alert: 1.0.3
  dropdown_below: ^1.0.3
  http: 0.12.2
  validators: 2.0.1
  firebase_core: ^0.5.2+1
  google_sign_in: 4.5.6
  firebase_auth: ^0.18.3+1
  fluttertoast: ^7.1.6
  get: 4.1.4
  quiver: ^2.1.5
  qr_code_scanner: ^0.2.1
  sliding_up_panel: ^1.0.2
  html_unescape: 1.0.2
  contacts_service: ^0.4.6
  flutter_map: any
  flutter_dash: ^0.0.1
  location: ^3.0.0
  flutter_open_whatsapp: ^0.1.2
  #image_picker: ^0.6.7+21
  image_cropper: ^1.3.1
  # flutrans: ^0.0.4
  firebase_messaging: #^7.0.3
  flutter_downloader: ^1.5.2
  flutter_datetime_picker: ^1.4.0
  flutter_uploader: ^1.2.1
  file_picker:
  # ext_storage: ^1.0.3
  flutter_appavailability: ^0.0.21
  open_appstore: ^1.0.2
  video_player: ^1.0.1
  # flick_video_player: 0.1.0
  chewie: ^ 0.12.2
  better_player: ^0.0.61
  oktoast: ^3.0.0
  flutter_rating_bar: ^4.0.0
  video_thumbnail: ^0.3.3
  fl_chart: ^0.36.1
  cached_network_image: ^2.4.0
  substring_highlight: ^1.0.33
  snapping_sheet: ^3.1.0
  scroll_to_index: ^2.1.0
  timelines: ^0.1.0
  another_flushbar: ^1.12.29
  contact_picker: ^0.0.2
  string_validator: ^0.1.3
  grouped_list: ^5.1.2
  package_info_plus: ^0.6.4
  geocoder: ^0.2.1
  flutter_tawk: ^0.0.5
  number_to_words_english: ^2.0.2
  flutter_filereader: ^3.0.0
  email_validator : ^2.1.16
  open_file: ^3.0.1
  flutter_pdfview: 1.0.4
  simple_shadow : 0.3.0
  timeago: ^2.0.30
  flutter_staggered_grid_view: ^0.6.2
  modal_bottom_sheet : ^1.0.0+1
  firebase_dynamic_links : ^0.6.3
  device_info_plus: ^0.7.2
  bot_toast:
  flutter_bloc:
  hydrated_bloc:
  readmore: 2.1.0
  mime: ^0.9.7
  tutorial_coach_mark: ^0.6.0+1
  shimmer: ^2.0.0
  hive: ^1.1.4+1

  azlogistik_chat:
    path: ./az_chat
  
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/detail_compro_buyer/
    - assets/template_buyer/
    - lib/app/modules/ARK/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
        - asset: assets/fonts/AvenirNextLTPro-Medium.otf
          weight: 500
        - asset: assets/fonts/AvenirNextLTPro-Demi.otf
          weight: 600
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages