import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'kode_bahasa': 'en',
          'kode_bahasa_API': 'en_US',
          'IntroHal1LabelTitle':
              'Welcome to Muatmuat platform ekosistem logistik di Indonesia',
          'IntroHal1LabelSubTitle': '',
          'IntroHal1LabelDesc':
              'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper s',
          'IntroHal2LabelTitle': 'What is Muatmuat?',
          'IntroHal2LabelSubTitle': '',
          'IntroHal2LabelDesc':
              'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper s',
          'IntroHal3LabelTitle': 'Benefits of Joining Us',
          'IntroHal3LabelSubTitle': '',
          'IntroHal3LabelDesc':
              'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper s',
          'IntroButtonNext': 'Next',
          'IntroButtonBack': 'Back',
          'IntroButtonSkip': 'Skip',
          'Intro2LabelTitle': 'Jalan Mudah Bersama',
          'Intro2LabelSubTitle': 'Platform Ekosistem Logistik di Indonesia',
          'Intro2LoginButton': 'Login',
          'Intro2SignUpButton': 'Sign Up',
          'RegisterLabelTitle': 'Create an Account',
          'RegisterLabelEdtFullName': 'Full name',
          'RegisterLabelEdtValidatorFullNameEmpty': 'You must fill Full name',
          'RegisterLabelEdtEmail': 'Email',
          'RegisterLabelEdtValidatorEmailFalseFormat':
              'Enter an email address in the correct format',
          'RegisterLabelEdtValidatorEmailEmpty': 'You must fill Email',
          'RegisterLabelEdtValidatorDuplicateEmail':
              'Email has been registered',
          'RegisterLabelEdtPhoneNumber': 'Phone Number',
          'RegisterLabelEdtValidatorPhoneNumberEmpty':
              'You must fill Phone Number',
          'RegisterLabelEdtValidatorPhoneNumberFalseFormat':
              'Minimum 10 digits phone number',
          'RegisterLabelEdtValidatorDuplicatePhoneNumber':
              'Phone number has been registered',
          'RegisterLabelEdtPassword': 'Password',
          'RegisterLabelEdtValidatorPasswordEmpty': 'You must fill Password',
          'RegisterLabelEdtValidatorPasswordMinChar':
              'The minimum character for the password is 8',
          'RegisterLabelEdtValidatorPasswordFalseFormat':
              'Your password must consist of a combination of uppercase, lowercase and numbers',
          'RegisterLabelEdtConfirmPassword': 'Confirm Password',
          'RegisterLabelEdtValidatorConfirmPasswordEmpty':
              'You must fill Confirm Password',
          'RegisterLabelEdtValidatorConfirmPasswordNotSame':
              'Password do not match',
          'RegisterLabelEdtReferralCode': 'Referral Code (If you have)',
          'RegisterButtonSignUp': 'Sign Up',
          'RegisterLabelOr': 'or',
          'RegisterLabelAlreadyHaveAccount': 'Already Have Account? ',
          'RegisterLabelDialogLoading': 'Please wait',
          'RegisterButtonLogin': 'Sign In',
          'RegisterLabelErrorRegister': 'Register failed',
          'LoginLabelEdtEmail': 'Email',
          'LoginLabelEdtPassword': 'Password',
          'LoginButtonLogin': 'Login',
          'LoginLabelOr': 'or',
          'LoginLabelForgotPassword': 'Forgot Password?',
          'LoginButtonResetPassword': 'Reset Password',
          'LoginLabelDontHaveAccount': 'Don\'t Have Account?',
          'LoginLabelDialogLoading': 'Please wait',
          'LoginLabelEdtValidatorPasswordEmpty': 'You must fill Password',
          'LoginLabelEdtValidatorEmailEmpty': 'You must fill Email',
          'LoginLabelEdtValidatorEmailFalseFormat':
              'Isi email dengan format yang benar',
          'LoginButtonRegister': 'Sign Up',
          'LoginLabelErrorLogin':
              'Wrong email or password. Please check again.',
          'VerifyEmailLabelSendCode':
              'Verification code has been sent to your email. Please check the message in your email.',
          'VerifyEmailLabelCountdown': 'The activation link will end in ',
          'VerifyEmailLabelMinutes': 'Menit',
          'VerifyEmailLabelSeconds': 'Detik',
          'VerifyEmailLabelExpired':
              'The verification code has expired. Please resend the verification code.',
          'VerifyEmailButtonResendCode': 'Resend Verification Code',
          'VerifyEmailLabelAlreadyVerified': 'Email successfully verified',
          'VerifyEmailButtonOK': 'OK',
          'VerifyEmailLabelConfirmationBack':
              'Are you sure to cancel your register?',
          'VerifyHPLabelSendCode':
              'Your email has been successfully activated, please check the message on your device to continue registration',
          'VerifyHPLabelYourPhoneNumber': 'Your phone number',
          'VerifyHPButtonChangePhoneNumber': 'Change',
          'VerifyHPLabelCountdown': 'The activation link will end in ',
          'VerifyHPLabelMinutes': 'minute',
          'VerifyHPLabelSeconds': 'second',
          'VerifyHPLabelExpired':
              'The verification code has expired. Please resend the verification code.',
          'VerifyHPButtonResendCode': 'Resend Verification Code',
          'VerifyHPButtonTryAgain': 'Try Again',
          'VerifyHPLabelSuccessVerified':
              'Phone number has been successfully verified',
          'VerifyHPLabelDialogTitleChangePhoneNumber': 'Change Phone Number',
          'VerifyHPLabelEdtDialogChange': 'Phone Number',
          'VerifyHPLabelEdtValidatorPhoneNumberEmpty':
              'You must fill Phone Number',
          'VerifyHPLabelEdtValidatorPhoneNumberFalseFormat':
              'Minimum 10 digits phone number',
          'VerifyHPButtonDialogChange': 'Change',
          'VerifyHPLabelDialogSuccessChangePhoneNumber':
              'Phone number has been successfully changed',
          'VerifyHPButtonOK': 'OK',
          'VerifyHPLabelConfirmationBack':
              'Are you sure to cancel your phone verification?',
          'TACLabelTitle': 'Terms and Conditions',
          'TACLabelErrorCheck':
              'Please check all aspects of the terms and conditions',
          'TACLabelAgreeTerms': 'I agree',
          'TACButtonNext': 'Agree',
          'PAPLabelTitle': 'Privacy dan Policy',
          'PAPLabelErrorCheck':
              'Please check all aspects of the privacy and policy',
          'PAPLabelAgree': 'I agree',
          'PAPButtonNext': 'Agree',
          'HomeLabelBalance': 'Balance',
          'HomeLabelButtonPay': 'Pay',
          'HomeLabelButtonRequest': 'Request',
          'HomeLabelButtonTopUp': 'Top-Up',
          'HomeLabelButtonReward': 'Rewards',
          'HomeLabelMenuLogistic': 'Logistic',
          'HomeLabelMenuLogisticDesc': '5 Service Available',
          'HomeLabelMenuSupport': 'Support',
          'HomeLabelMenuSupportDesc': '5 Service Available',
          'HomeLabelMenuArticles': 'Articles',
          'HomeLabelMenuArticlesSeeMore': 'See More',
          'HomeLabelMenuArticlesReadMore': 'Read more',
          'HomeLabelLogisticBigFleets': 'BigFleets',
          'HomeLabelLogisticMuatTrans': 'MuatTrans',
          'HomeLabelLogisticTransportMarket': 'Transport Market',
          'HomeLabelLogisticTMS': 'TMS',
          'HomeLabelLogisticWarehouse': 'Warehouse',
          'HomeLabelSupportMerchants': 'Merchants',
          'HomeLabelSupportMarket': 'Market',
          'HomeLabelSupportDealershipWorkshop': 'Dealership & Workshop',
          'HomeLabelSupportFinanceInsurance': 'Finance & Insurance',
          'HomeLabelSupportHumanCapital': 'Human Capital',
          'ResetPasswordLabelSuccessSentPassword':
              'The link to reset the password has been sent to your email. Please check the message in your email.',
          'ResetPasswordButtonOK': 'OK',
          'ResetPasswordLabelEdtEmail': 'Email',
          'ResetPasswordLabelEdtValidatorEmailFalseFormat':
              'Enter an email address in the correct format',
          'ResetPasswordLabelEdtValidatorEmailEmpty': 'You must fill Email',
          'ResetPasswordButtonResetPassword': 'Reset Password',
          'GlobalLabelError': 'Error',
          'GlobalLabelSuccess': 'Success',
          'GlobalLabelErrorNoConnection':
              'There is no internet connection. Please check your data plan, WiFi, or network at your place',
          'GlobalLabelErrorNullResponse':
              'There was an error when retrieving data.',
          'GlobalButtonTryAgain': 'Try Again',
          'GlobalButtonOK': 'OK',
          'GlobalLabelDialogLoading': 'Please wait...',
          'GlobalLabelErrorFalseTokenApp':
              'Your account is logged in on another device',
          'GlobalButtonYES': 'YES',
          'GlobalButtonNO': 'NO',
          'GlobalLabelBackAgainExit': 'Press back again to exit',
          'SettingLabelConfirmationLogOut': 'Are you sure you want to log out?',
          'SettingLabelLanguage': 'Language',
          'SettingLabelLogout': 'Logout',
          'Notif': 'Notification',
          'title': 'Title',
          'message': 'Message',
          'LTRSearchLabelPickup': 'Pickup location',
          'LTRSearchLabelDestination': 'Destination location',
          'LTRSearchLabelTypeOfTruck': 'Type of truck',
          'LTRSearchLabelSelectTypeOfTruck': 'Select Type of truck',
          'LTRSearchLabelNumberOfTruck': 'Number of truck',
          'LTRSearchButtonSearch': 'Search',
          'LTRResultLabelSearchResult': 'Search Result',
          'LTRResultLabelAreaPickup': 'Area Pickup',
          'LTRResultLabelDestination': 'Destination',
          'LTRResultLabelTruck': 'Truck',
          'LTRResultLabelUnit': 'Unit',
          'LTRResultLabelDetailTransporter': 'Detail Transporter',
          'LTRResultLabelCallTransporter': 'Call Transporter',
          //old
          //     'nama_lengkap': 'Full Name',
          // 'email': 'Email',
          // 'no_telp': 'Phone Number',
          // 'password': 'Password',
          // 'konfirmasi_password': 'Retype Password',
          // 'kode_referal': 'Referal Code (If available)',
          // 'pesan_nama_lengkap': 'You must fill Full name',
          // 'pesan_email': 'You must fill Email',
          // 'pesan_email_tidak_sesuai_format':
          //     'Enter an email address in the correct format',
          // 'pesan_no_telp': 'You must fill Phone Number',
          // 'pesan_password': 'You must fill Password',
          // 'pesan_konfirmasi_password': 'You must fill Retype Password',
          // 'pesan_password_tidak_sama': 'Password do not match',
          // 'belum_punya_akun': 'Don\'t Have Account? ',
          // 'daftar': 'Sign Up',
          // 'selamat_datang': 'Welcome',
          // 'jalan_mudah_bersama': 'Jalan Mudah Bersama',
          // 'login': 'Login',
          // 'lupa_password': 'Forgot Password? ',
          // 'reset_password': 'Reset Password',
          // 'daftar_akun': 'Register',
          // 'sudah_punya_akun': 'Already Have Account? ',
          // 'masuk_disini': 'Sign In',
          // 'login_gagal': 'Wrong email or password. Please check again.',
          // 'daftar_berhasil': 'Register success',
          // 'daftar_gagal': 'Register failed',
          // 'kirim_ulang_verifikasi': 'Resend Verification Code',
          // 'link_aktivasi_akan_berakhir': 'The activation link will end in ',
          // 'link_aktivasi_telah_berakhir': 'The activation link will end in ',
          // 'menit': 'minute',
          // 'detik': 'second',
          // 'pesan_sudah_dikirim_kode_verifikasi':
          //     'Verification code has been sent to your email. Please check the message in your email.',
          // 'email_anda': 'Your email',
          // 'email_sudah_terverifikasi': 'Email successfully verified',
          // 'pesan_kode_verifikasi_expired':
          //     'The verification code has expired. Please resend the verification code.',
          // 'pesan_password_kurang_dari_8':
          //     'The minimum character for the password is 8',
          // 'pesan_password_harus_ada_huruf_besar_kecil_angka':
          //     'Your password must consist of a combination of uppercase, lowercase and numbers',

          // 'pesan_baris_1_verifikasi_telp':
          //     'Your email has been successfully activated, please check the message on your device to continue registration',
          // 'pesan_baris_2_verifikasi_telp': 'Your phone number',
          // 'telp_sudah_terverifikasi':
          //     'Phone number has been successfully verified',
          // 'pesan_no_telp_min_10_angka': 'Minimum 10 digits phone number',
          // 'pesan_sukses_kirim_reset_password':
          //     'The link to reset the password has been sent to your email. Please check the message in your email.',
          // 'ubah_no_telp': 'Change Phone Number ',
          // 'ubah': 'Change',
          // 'pesan_error_response_null':
          //     'There was an error when retrieving data.',
          // 'judul_error_dialog': 'ERROR',
          // 'judul_success_dialog': 'SUCCESS',
          // 'pesan_success_ubah_no_telp':
          //     'Phone number has been successfully changed',
          // 'ganti_no_telp': 'Change',
          // 'pesan_tidak_ada_koneksi':
          //     'There is no internet connection. Please check your data plan, WiFi, or network at your place',
          // 'coba_lagi': 'Try Again',
          // 'privasi_dan_kebijakan': "Privacy and Policies",
          // 'saldo': 'Balance', //'Saldo',
          // 'lihat_semua': 'See More',
          // 'artikel': 'Articles',
          // 'judul_logistik': 'Logistic',
          // 'judul_support': 'Support',
          // 'deskripsi_menu_logistik': '5 Service Available',
          // 'deskripsi_menu_support': '5 Service Available',
          // 'judul_reward': 'Reward',
          // 'judul_top-up': 'Top-Up',
          // 'judul_request': 'Request',
          // 'judul_pay': 'Pay',
          // 'baca_selanjutnya': 'Read more',
          // 'atau': 'or',
          // 'judul_daftar_akun': 'Create an Account',
          // 'pesan_harus_dicentang_syarat_dan_ketentuan':
          //     'Please check all aspects of the terms and conditions',
          // 'pesan_harus_dicentang_privasi_dan_kebijakan':
          //     'Please check all aspects of privacy and policy',
        },
        'id': {
          'kode_bahasa': 'id',
          'kode_bahasa_API': 'id_ID',
          'IntroHal1LabelTitle':
              'Selamat Datang di Muatmuat platform ekosistem logistik di Indonesia',
          'IntroHal1LabelSubTitle': '',
          'IntroHal1LabelDesc':
              'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper s',
          'IntroHal2LabelTitle': 'Apa itu Muatmuat?',
          'IntroHal2LabelSubTitle': '',
          'IntroHal2LabelDesc':
              'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper s',
          'IntroHal3LabelTitle': 'Keuntungan Bergabung Bersama Kami',
          'IntroHal3LabelSubTitle': '',
          'IntroHal3LabelDesc':
              'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper s',
          'IntroButtonNext': 'Next',
          'IntroButtonBack': 'Back',
          'IntroButtonSkip': 'Skip',
          'Intro2LabelTitle': 'Jalan Mudah Bersama',
          'Intro2LabelSubTitle': 'Platform Ekosistem Logistik di Indonesia',
          'Intro2LoginButton': 'Masuk',
          'Intro2SignUpButton': 'Daftar Akun',
          'RegisterLabelTitle': 'Daftar Akun',
          'RegisterLabelEdtFullName': 'Nama Lengkap',
          'RegisterLabelEdtValidatorFullNameEmpty': 'Nama lengkap harus diisi',
          'RegisterLabelEdtEmail': 'Email',
          'RegisterLabelEdtValidatorEmailFalseFormat':
              'Isi email dengan format yang benar',
          'RegisterLabelEdtValidatorEmailEmpty': 'Email harus diisi',
          'RegisterLabelEdtValidatorDuplicateEmail': 'Email sudah terdaftar',
          'RegisterLabelEdtPhoneNumber': 'Nomor Handphone',
          'RegisterLabelEdtValidatorPhoneNumberEmpty':
              'Nomor telepon harus diisi',
          'RegisterLabelEdtValidatorPhoneNumberFalseFormat':
              'Nomor telepon minimal 10 angka',
          'RegisterLabelEdtValidatorDuplicatePhoneNumber':
              'No Handphone sudah terdaftar',
          'RegisterLabelEdtPassword': 'Password',
          'RegisterLabelEdtValidatorPasswordEmpty': 'Kata sandi harus diisi',
          'RegisterLabelEdtValidatorPasswordMinChar':
              'Minimal password 8 karakter',
          'RegisterLabelEdtValidatorPasswordFalseFormat':
              'Password anda harus terdiri dari perpaduan huruf besar, huruf kecil dan angka',
          'RegisterLabelEdtConfirmPassword': 'Confirm Password',
          'RegisterLabelEdtValidatorConfirmPasswordEmpty':
              'Ulangi kata sandi harus diisi',
          'RegisterLabelEdtValidatorConfirmPasswordNotSame':
              'Kata sandi tidak sama',
          'RegisterLabelEdtReferralCode': 'Kode Referral (Jika Ada)',
          'RegisterButtonSignUp': 'Daftar Akun',
          'RegisterLabelOr': 'or',
          'RegisterLabelAlreadyHaveAccount': 'Sudah Punya Akun?',
          'RegisterLabelDialogLoading': 'Tunggu Sebentar',
          'RegisterButtonLogin': 'Masuk disini',
          'RegisterLabelErrorRegister': 'Daftar gagal',
          'LoginLabelEdtEmail': 'Email',
          'LoginLabelEdtPassword': 'Password',
          'LoginButtonLogin': 'Masuk',
          'LoginLabelOr': 'Atau',
          'LoginLabelForgotPassword': 'Lupa Password?',
          'LoginButtonResetPassword': 'Reset Password',
          'LoginLabelDontHaveAccount': 'Belum punya akun?',
          'LoginLabelDialogLoading': 'Tunggu Sebentar',
          'LoginLabelEdtValidatorPasswordEmpty': 'Password harus diisi',
          'LoginLabelEdtValidatorEmailEmpty': 'Email harus diisi',
          'LoginLabelEdtValidatorEmailFalseFormat':
              'Isi email dengan format yang benar',
          'LoginButtonRegister': 'Daftar disini',
          'LoginLabelErrorLogin':
              'Email atau password salah. Mohon dicek kembali.',
          'VerifyEmailLabelSendCode':
              'Kode verifikasi sudah dikirim ke email Anda. Mohon cek pesan di email Anda.',
          'VerifyEmailLabelCountdown': 'Link aktivasi akan berakhir dalam ',
          'VerifyEmailLabelMinutes': 'Menit',
          'VerifyEmailLabelSeconds': 'Detik',
          'VerifyEmailLabelExpired':
              'Kode verifikasi sudah kadaluarsa. Silahkan kirim ulang kode verifikasi.',
          'VerifyEmailButtonResendCode': 'Kirim Ulang Verifikasi',
          'VerifyEmailLabelAlreadyVerified': 'Email berhasil terverifikasi',
          'VerifyEmailButtonOK': 'OK',
          'VerifyEmailLabelConfirmationBack':
              'Apakah Anda yakin akan membatalkan pendaftaran?',
          'VerifyHPLabelSendCode':
              'Email anda berhasil di aktivasi, mohon cek pesan di perangkat anda untuk melanjutkan pendaftaran',
          'VerifyHPLabelYourPhoneNumber': 'No Handphone Anda',
          'VerifyHPButtonChangePhoneNumber': 'Ganti',
          'VerifyHPLabelCountdown': 'Link aktivasi akan berakhir dalam ',
          'VerifyHPLabelMinutes': 'Menit',
          'VerifyHPLabelSeconds': 'Detik',
          'VerifyHPLabelExpired':
              'Kode verifikasi sudah kadaluarsa. Silahkan kirim ulang kode verifikasi.',
          'VerifyHPButtonResendCode': 'Kirim Ulang Verifikasi',
          'VerifyHPButtonTryAgain': 'Coba lagi',
          'VerifyHPLabelSuccessVerified': 'No Handphone berhasil terverifikasi',
          'VerifyHPLabelDialogTitleChangePhoneNumber': 'Ganti No Handphone',
          'VerifyHPLabelEdtDialogChange': 'No Handphone',
          'VerifyHPLabelEdtValidatorPhoneNumberEmpty':
              'Nomor telepon harus diisi',
          'VerifyHPLabelEdtValidatorPhoneNumberFalseFormat':
              'Nomor telepon minimal 10 angka',
          'VerifyHPButtonDialogChange': 'Ubah',
          'VerifyHPLabelDialogSuccessChangePhoneNumber':
              'No Handphone berhasil diubah',
          'VerifyHPButtonOK': 'OK',
          'VerifyHPLabelConfirmationBack':
              'Apakah Anda yakin untuk membatalkan verifikasi No Handphone Anda?',
          'TACLabelTitle': 'Terms and Conditions',
          'TACLabelErrorCheck':
              'Mohon mencentang semua aspek syarat dan ketentuan',
          'TACLabelAgree': 'Saya Setuju',
          'TACButtonAgree': 'Setuju',
          'PAPLabelTitle': 'Privasi dan Kebijakan',
          'PAPLabelErrorCheck':
              'Mohon mencentang semua aspek syarat dan ketentuan',
          'PAPLabelAgree': 'Saya Setuju',
          'PAPButtonAgree': 'Setuju',
          'HomeLabelBalance': 'Saldo',
          'HomeLabelButtonPay': 'Pay',
          'HomeLabelButtonRequest': 'Request',
          'HomeLabelButtonTopUp': 'Top-Up',
          'HomeLabelButtonReward': 'Hadiah',
          'HomeLabelMenuLogistic': 'Logistik',
          'HomeLabelMenuLogisticDesc': '5 Jasa yang tersedia',
          'HomeLabelMenuSupport': 'Bantuan',
          'HomeLabelMenuSupportDesc': '5 Jasa yang tersedia',
          'HomeLabelMenuArticles': 'Articles',
          'HomeLabelMenuArticlesSeeMore': 'Lihat Semua',
          'HomeLabelMenuArticlesReadMore': 'Selanjutnya',
          'HomeLabelLogisticBigFleets': 'BigFleets',
          'HomeLabelLogisticMuatTrans': 'MuatTrans',
          'HomeLabelLogisticTransportMarket': 'Transport Market',
          'HomeLabelLogisticTMS': 'TMS',
          'HomeLabelLogisticWarehouse': 'Warehouse',
          'HomeLabelSupportMerchants': 'Merchants',
          'HomeLabelSupportMarket': 'Market',
          'HomeLabelSupportDealershipWorkshop': 'Dealership & Workshop',
          'HomeLabelSupportFinanceInsurance': 'Finance & Insurance',
          'HomeLabelSupportHumanCapital': 'Human Capital',
          'ResetPasswordLabelSuccessSentPassword':
              'Link untuk me-reset password sudah terkirim ke email anda. Silahkan cek pesan di email anda.',
          'ResetPasswordButtonOK': 'OK',
          'ResetPasswordLabelEdtEmail': 'Email',
          'ResetPasswordLabelEdtValidatorEmailFalseFormat':
              'Isi email dengan format yang benar',
          'ResetPasswordLabelEdtValidatorEmailEmpty': 'Email harus diisi',
          'ResetPasswordButtonResetPassword': 'Reset Password',
          'GlobalLabelError': 'Error',
          'GlobalLabelSuccess': 'Success',
          'GlobalLabelErrorNoConnection':
              'Tidak ada koneksi internet. Mohon cek ulang paket data, WiFi, atau jaringan di tempatmu',
          'GlobalLabelErrorNullResponse':
              'Terdapat kesalahan ketika ambil data.',
          'GlobalButtonTryAgain': 'Coba lagi',
          'GlobalButtonOK': 'OK',
          'GlobalLabelDialogLoading': 'Please wait...',
          'GlobalLabelErrorFalseTokenApp': 'Akun anda login di device lain',
          'GlobalButtonYES': 'YA',
          'GlobalButtonNO': 'TIDAK',
          'GlobalLabelBackAgainExit': 'Tekan kembali lagi untuk keluar',
          'SettingLabelConfirmationLogOut': 'Apakah anda yakin ingin keluar?',
          'SettingLabelLanguage': 'Bahasa',
          'SettingLabelLogout': 'Keluar akun',
          'notif': 'Notifikasi',
          'title': 'Judul',
          'message': 'Pesan',
          'LTRSearchLabelPickup': 'Lokasi pengambilan barang',
          'LTRSearchLabelDestination': 'Lokasi tujuan',
          'LTRSearchLabelTypeOfTruck': 'Jenis truk',
          'LTRSearchLabelSelectTypeOfTruck': 'Pilih jenis truk',
          'LTRSearchLabelNumberOfTruck': 'Jumlah truk',
          'LTRSearchButtonSearch': 'Cari',
          'LTRResultLabelSearchResult': 'Hasil pencarian',
          'LTRResultLabelAreaPickup': 'Area Pengambilan barang',
          'LTRResultLabelDestination': 'Tujuan',
          'LTRResultLabelTruck': 'Truk',
          'LTRResultLabelUnit': 'Unit',
          'LTRResultLabelDetailTransporter': 'Detail Transporter',
          'LTRResultLabelCallTransporter': 'Hubungi Transporter',
          //old
          // 'nama_lengkap': 'Nama Lengkap',
          // 'email': 'Email',
          // 'no_telp': 'Nomor Telepon',
          // 'password': 'Kata Sandi',
          // 'konfirmasi_password': 'Ulangi Kata Sandi',
          // 'kode_referal': 'Kode Referal (Jika ada)',
          // 'pesan_nama_lengkap': 'Nama lengkap harus diisi',
          // 'pesan_email': 'Email harus diisi',
          // 'pesan_email_tidak_sesuai_format':
          //     'Isi email dengan format yang benar',
          // 'pesan_no_telp': 'Nomor telepon harus diisi',
          // 'pesan_password': 'Kata sandi harus diisi',
          // 'pesan_konfirmasi_password': 'Ulangi kata sandi harus diisi',
          // 'pesan_password_tidak_sama': 'Kata sandi tidak sama',
          // 'belum_punya_akun': 'Belum Punya Akun? ',
          // 'daftar': 'Daftar disini',
          // 'selamat_datang': 'Selamat Datang',
          // 'jalan_mudah_bersama': 'Jalan Mudah Bersama',
          // 'login': 'Masuk',
          // 'lupa_password': 'Lupa Kata Sandi? ',
          // 'reset_password': 'Atur Ulang Kata Sandi',
          // 'daftar_akun': 'Daftar Akun',
          // 'sudah_punya_akun': 'Sudah Punya Akun? ',
          // 'masuk_disini': 'Masuk disini',
          // 'login_gagal': 'email atau password salah. Mohon dicek kembali.',
          // 'daftar_berhasil': 'Daftar berhasil',
          // 'daftar_gagal': 'Daftar gagal',
          // 'kirim_ulang_verifikasi': 'Kirim Ulang Verifikasi',
          // 'link_aktivasi_akan_berakhir': 'Link aktivasi akan berakhir dalam ',
          // 'menit': 'menit',
          // 'detik': 'detik',
          // 'pesan_sudah_dikirim_kode_verifikasi':
          //     'Kode verifikasi sudah dikirim ke email Anda. Mohon cek pesan di email Anda.',
          // 'email_anda': 'Email Anda',
          // 'email_sudah_terverifikasi': 'Email berhasil terverifikasi',
          // 'pesan_kode_verifikasi_expired':
          //     'Kode verifikasi sudah kadaluarsa. Silahkan kirim ulang kode verifikasi.',
          // 'pesan_password_kurang_dari_8': 'Minimal password 8 karakter',
          // 'pesan_password_harus_ada_huruf_besar_kecil_angka':
          //     'Password anda harus terdiri dari perpaduan huruf besar, huruf kecil dan angka',
          // 'pesan_baris_1_verifikasi_telp':
          //     'Email anda berhasil di aktivasi, mohon cek pesan di perangkat anda untuk melanjutkan pendaftaran',
          // 'pesan_baris_2_verifikasi_telp': 'No Handphone Anda',
          // 'telp_sudah_terverifikasi': 'No Handphone berhasil terverifikasi',
          // 'pesan_no_telp_min_10_angka': 'Nomor telepon minimal 10 angka',
          // 'pesan_sukses_kirim_reset_password':
          //     'Link untuk me-reset password sudah terkirim ke email anda. Silahkan cek pesan di email anda.',
          // 'ubah_no_telp': 'Ganti No Handphone ',
          // 'ubah': 'Ubah',
          // 'pesan_error_response_null': 'Terdapat kesalahan ketika ambil data.',
          // 'judul_error_dialog': 'ERROR',
          // 'judul_success_dialog': 'SUCCESS',
          // 'pesan_success_ubah_no_telp': 'No Handphone berhasil diubah',
          // 'ganti_no_telp': 'Ganti',
          // 'pesan_tidak_ada_koneksi':
          //     'Tidak ada koneksi internet. Mohon cek ulang paket data, WiFi, atau jaringan di tempatmu',
          // 'coba_lagi': 'Coba lagi',
          // 'privasi_dan_kebijakan': "Privasi dan Kebijakan",
          // 'saldo': 'Saldo', //'Saldo',
          // 'lihat_semua': 'Lihat Semua',
          // 'artikel': 'Artikel',
          // 'judul_logistik': 'Logistik',
          // 'judul_support': 'Bantuan',
          // 'deskripsi_menu_logistik': '5 Jasa yang tersedia',
          // 'deskripsi_menu_support': '5 Jasa yang tersedia',
          // 'judul_reward': 'Hadiah',
          // 'judul_top-up': 'Top-Up',
          // 'judul_request': 'Request',
          // 'judul_pay': 'Bayar',
          // 'baca_selanjutnya': 'Selanjutnya',
          // 'atau': 'atau',
          // 'judul_daftar_akun': 'Daftar Akun',
          // 'pesan_harus_dicentang_syarat_dan_ketentuan':
          //     'Mohon mencentang semua aspek syarat dan ketentuan',
          // 'pesan_harus_dicentang_privasi_dan_kebijakan':
          //     'Mohon mencentang semua aspek privasi dan kebijakan',
        }
      };
}
